email_bucket             = "artistdirectory-email"
info_email               = "info@artistdirectory.com"
support_email            = "support@artistdirectory.com"
abuse_forwarding_email   = "chad@neatowebsolutions.com"
info_forwarding_email    = "chad@neatowebsolutions.com"
support_forwarding_email = "chad@neatowebsolutions.com"
